#############################################################################
# Makefile for building: libPluginShells.dylib.1.0.0
# Generated by qmake (2.01a) (Qt 4.6.0) on: Tue Sep 8 18:01:51 2009
# Project:  shells.pro
# Template: lib
# Command: /usr/local/Trolltech/Qt-4.6.0/bin/qmake -spec /usr/local/Trolltech/Qt-4.6.0/mkspecs/macx-g++ -macx -o Makefile shells.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc -arch i386
CXX           = g++ -arch i386
DEFINES       = -DSOFA_QT4 -DSOFA_DEV -DSOFA_GUI_QTVIEWER -DSOFA_GUI_GLUT -DSOFA_DUMP_VISITOR_INFO -DSOFA_HAVE_ZLIB -DSOFA_HAVE_PNG -DSOFA_HAVE_GLEW -DNDEBUG -DSOFA_XML_PARSER_TINYXML -DSOFA_GUI_QT -DMINI_FLOWVR -DSOFA_BUILD_SHELLS
CFLAGS        = -pipe -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.6.0/mkspecs/macx-g++ -I. -I../../../include -I../../../framework -I../../../modules -I../../../applications -I../../../extlibs/miniBoost -I../../../extlibs/tinyxml -I../../../extlibs/newmat -I../../../extlibs/qwt-5.2.0/src -I../../../extlibs/miniFlowVR/include -I../../../extlibs
LINK          = g++ -arch i386
LFLAGS        = -headerpad_max_install_names -L/System/Library/Frameworks/ -Wl,-rpath,@loader_path -Wl,-rpath,@executable_path/../lib/macx -Wl,-rpath,@executable_path/../../../../lib/macx -single_module -dynamiclib -compatibility_version	1.0 -current_version	1.0.0 -install_name	@rpath/libPluginShells.dylib.1
LIBS          = $(SUBLIBS)  -L../../../lib/macx -L../../../lib/sofa-plugins -lsofacomponentmastersolver -lsofacomponentfem -lsofacomponentinteractionforcefield -lsofacomponentcontextobject -lsofacomponentbehaviormodel -lsofacomponentengine -lsofacomponentlinearsolver -lsofacomponentodesolver -lsofacomponentbase -lsofacomponentloader -lsofacomponentcontroller -lsofacomponentvisualmodel -lsofacomponentmass -lsofacomponentforcefield -lsofacomponentmapping -lsofacomponentconstraint -lsofacomponentcollision -lsofacomponentmisc -lsofacomponent -lsofasimulation -lsofatree -lsofaautomatescheduler -lsofacomponentmastersolver -lsofacomponentfem -lsofacomponentinteractionforcefield -lsofacomponentcontextobject -lsofacomponentbehaviormodel -lsofacomponentengine -lsofacomponentlinearsolver -lsofacomponentodesolver -lsofacomponentbase -lsofacomponentloader -lsofacomponentcontroller -lsofacomponentvisualmodel -lsofacomponentmass -lsofacomponentforcefield -lsofacomponentmapping -lsofacomponentconstraint -lsofacomponentcollision -lsofacomponentmisc -lsofacomponent -lsofasimulation -lsofatree -lsofaautomatescheduler -lsofahelper -lsofadefaulttype -lsofacore -lsofahelper -lsofadefaulttype -lsofacore -lpthread -framework OpenGL -framework GLUT -ltinyxml -lz -lpng -lnewmat -lGLEW -lminiFlowVR -lpthread -framework OpenGL -framework GLUT -ltinyxml -lz -lpng -lnewmat -lGLEW -lminiFlowVR 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/Trolltech/Qt-4.6.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.5

####### Output directory

OBJECTS_DIR   = OBJ/release/

####### Files

SOURCES       = forcefield/TriangularBendingFEMForceField.cpp \
		mapping/BendingPlateMechanicalMapping.cpp 
OBJECTS       = OBJ/release/TriangularBendingFEMForceField.o \
		OBJ/release/BendingPlateMechanicalMapping.o
DIST          = /usr/local/Trolltech/Qt-4.6.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/common/mac.conf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/common/mac-g++.conf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/mac/default_pre.prf \
		../../../sofa-local.cfg \
		../../../sofa.cfg \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/dll.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/shared.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/warn_on.prf \
		shells.pro
QMAKE_TARGET  = PluginShells
DESTDIR       = ../../../lib/sofa-plugins/
TARGET        = libPluginShells.dylib.1.0.0
TARGETA       = ../../../lib/sofa-plugins/libPluginShells.a
TARGETD       = libPluginShells.dylib.1.0.0
TARGET0       = libPluginShells.dylib
TARGET1       = libPluginShells.dylib.1
TARGET2       = libPluginShells.dylib.1.0

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  ../../../lib/sofa-plugins/$(TARGET)

../../../lib/sofa-plugins/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@$(CHK_DIR_EXISTS) ../../../lib/sofa-plugins/ || $(MKDIR) ../../../lib/sofa-plugins/ 
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) ../../../lib/sofa-plugins/$(TARGET)
	-$(DEL_FILE) ../../../lib/sofa-plugins/$(TARGET0)
	-$(DEL_FILE) ../../../lib/sofa-plugins/$(TARGET1)
	-$(DEL_FILE) ../../../lib/sofa-plugins/$(TARGET2)
	-$(MOVE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2) ../../../lib/sofa-plugins/
	cp PluginShells.txt ../../../lib/sofa-plugins



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)
	$(RANLIB) $(TARGETA)

Makefile: shells.pro  /usr/local/Trolltech/Qt-4.6.0/mkspecs/macx-g++/qmake.conf /usr/local/Trolltech/Qt-4.6.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/common/mac.conf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/common/mac-g++.conf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/mac/default_pre.prf \
		../../../sofa-local.cfg \
		../../../sofa.cfg \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/dll.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/shared.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/warn_on.prf
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.6.0/mkspecs/macx-g++ -macx -o Makefile shells.pro
/usr/local/Trolltech/Qt-4.6.0/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/common/mac.conf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/common/mac-g++.conf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/mac/default_pre.prf:
../../../sofa-local.cfg:
../../../sofa.cfg:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/mac/default_post.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/mac/objective_c.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/dll.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/shared.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/warn_on.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.6.0/mkspecs/macx-g++ -macx -o Makefile shells.pro

dist: 
	@$(CHK_DIR_EXISTS) OBJ/release/PluginShells1.0.0 || $(MKDIR) OBJ/release/PluginShells1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) OBJ/release/PluginShells1.0.0/ && (cd `dirname OBJ/release/PluginShells1.0.0` && $(TAR) PluginShells1.0.0.tar PluginShells1.0.0 && $(COMPRESS) PluginShells1.0.0.tar) && $(MOVE) `dirname OBJ/release/PluginShells1.0.0`/PluginShells1.0.0.tar.gz . && $(DEL_FILE) -r OBJ/release/PluginShells1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) ../../../lib/sofa-plugins/$(TARGET) 
	-$(DEL_FILE) ../../../lib/sofa-plugins/$(TARGET0) ../../../lib/sofa-plugins/$(TARGET1) ../../../lib/sofa-plugins/$(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_clean: 

####### Compile

OBJ/release/TriangularBendingFEMForceField.o: forcefield/TriangularBendingFEMForceField.cpp ../../../modules/sofa/component/forcefield/shells/TriangularBendingFEMForceField.inl \
		../../../modules/sofa/component/forcefield/shells/TriangularBendingFEMForceField.h \
		../../../framework/sofa/core/componentmodel/behavior/ForceField.h \
		../../../framework/sofa/core/core.h \
		../../../framework/sofa/helper/system/config.h \
		../../../framework/sofa/core/componentmodel/behavior/BaseForceField.h \
		../../../framework/sofa/core/objectmodel/BaseObject.h \
		../../../framework/sofa/core/objectmodel/Base.h \
		../../../framework/sofa/helper/system/SofaOStream.h \
		../../../framework/sofa/helper/helper.h \
		../../../framework/sofa/helper/vector.h \
		../../../framework/sofa/core/objectmodel/DataPtr.h \
		../../../framework/sofa/core/objectmodel/Data.h \
		../../../framework/sofa/core/objectmodel/BaseData.h \
		../../../framework/sofa/core/objectmodel/DDGNode.h \
		../../../framework/sofa/core/objectmodel/BaseObjectDescription.h \
		../../../framework/sofa/core/objectmodel/BaseContext.h \
		../../../framework/sofa/core/objectmodel/Tag.h \
		../../../framework/sofa/helper/set.h \
		../../../framework/sofa/core/objectmodel/ClassInfo.h \
		../../../framework/sofa/helper/FnDispatcher.h \
		../../../framework/sofa/defaulttype/SolidTypes.h \
		../../../framework/sofa/defaulttype/defaulttype.h \
		../../../framework/sofa/defaulttype/Vec.h \
		../../../framework/sofa/helper/fixed_array.h \
		../../../framework/sofa/helper/rmath.h \
		../../../framework/sofa/defaulttype/Quat.h \
		../../../framework/sofa/helper/Quater.h \
		../../../framework/sofa/defaulttype/Mat.h \
		../../../framework/sofa/defaulttype/SparseConstraintTypes.h \
		../../../framework/sofa/defaulttype/BaseMatrix.h \
		../../../framework/sofa/defaulttype/BaseVector.h \
		../../../framework/sofa/core/componentmodel/behavior/MechanicalState.h \
		../../../framework/sofa/core/componentmodel/behavior/BaseMechanicalState.h \
		../../../framework/sofa/core/componentmodel/behavior/State.h \
		../../../framework/sofa/defaulttype/DataTypeInfo.h \
		../../../framework/sofa/defaulttype/VecTypes.h \
		../../../framework/sofa/defaulttype/RigidTypes.h \
		../../../framework/sofa/core/componentmodel/topology/BaseMeshTopology.h \
		../../../framework/sofa/core/componentmodel/topology/Topology.h \
		../../../framework/sofa/core/objectmodel/DataFileName.h \
		../../../framework/sofa/helper/system/FileRepository.h \
		../../../modules/sofa/component/topology/TriangleData.h \
		../../../framework/sofa/helper/system/thread/CTime.h \
		../../../framework/sofa/core/componentmodel/behavior/ForceField.inl \
		../../../framework/sofa/helper/gl/template.h \
		../../../framework/sofa/helper/system/gl.h \
		../../../modules/sofa/component/topology/TriangleData.inl \
		../../../modules/sofa/component/topology/TriangleSetTopologyChange.h \
		../../../modules/sofa/component/topology/TetrahedronSetTopologyChange.h \
		../../../modules/sofa/component/topology/EdgeData.inl \
		../../../modules/sofa/component/topology/EdgeData.h \
		../../../modules/sofa/component/component.h \
		../../../modules/sofa/component/topology/EdgeSetTopologyChange.h \
		../../../modules/sofa/component/topology/QuadSetTopologyChange.h \
		../../../modules/sofa/component/topology/PointData.inl \
		../../../modules/sofa/component/topology/PointData.h \
		../../../modules/sofa/component/topology/PointSetTopologyChange.h \
		../../../modules/sofa/component/topology/HexahedronSetTopologyChange.h \
		../../../framework/sofa/helper/system/thread/debug.h \
		../../../framework/sofa/defaulttype/Vec3Types.h \
		../../../modules/sofa/component/container/MechanicalObject.h \
		../../../framework/sofa/core/objectmodel/XDataPtr.h \
		../../../framework/sofa/core/objectmodel/VDataPtr.h \
		../../../framework/sofa/defaulttype/LaparoscopicRigidTypes.h \
		../../../framework/sofa/core/componentmodel/behavior/Mass.h \
		../../../framework/sofa/core/componentmodel/behavior/BaseMass.h \
		../../../framework/sofa/core/ObjectFactory.h \
		../../../framework/sofa/core/objectmodel/ContextObject.h \
		../../../framework/sofa/core/VisualModel.h \
		../../../framework/sofa/core/BehaviorModel.h \
		../../../framework/sofa/core/CollisionModel.h \
		../../../framework/sofa/core/CollisionElement.h \
		../../../framework/sofa/core/BaseMapping.h \
		../../../framework/sofa/core/componentmodel/topology/TopologicalMapping.h \
		../../../framework/sofa/core/componentmodel/behavior/InteractionForceField.h \
		../../../framework/sofa/core/componentmodel/behavior/BaseConstraint.h \
		../../../framework/sofa/core/componentmodel/behavior/BaseLMConstraint.h \
		../../../framework/sofa/core/componentmodel/behavior/BaseMechanicalMapping.h \
		../../../framework/sofa/core/componentmodel/behavior/OdeSolver.h \
		../../../framework/sofa/core/componentmodel/behavior/MultiVector.h \
		../../../framework/sofa/core/componentmodel/behavior/MultiMatrix.h \
		../../../framework/sofa/core/componentmodel/behavior/LinearSolver.h \
		../../../framework/sofa/core/componentmodel/behavior/MasterSolver.h \
		../../../framework/sofa/core/componentmodel/topology/BaseTopologyObject.h \
		../../../framework/sofa/core/componentmodel/behavior/BaseController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OBJ/release/TriangularBendingFEMForceField.o forcefield/TriangularBendingFEMForceField.cpp

OBJ/release/BendingPlateMechanicalMapping.o: mapping/BendingPlateMechanicalMapping.cpp mapping/BendingPlateMechanicalMapping.inl \
		mapping/BendingPlateMechanicalMapping.h \
		../../../framework/sofa/core/componentmodel/behavior/MechanicalMapping.h \
		../../../framework/sofa/core/Mapping.h \
		../../../framework/sofa/core/BaseMapping.h \
		../../../framework/sofa/core/objectmodel/BaseObject.h \
		../../../framework/sofa/core/objectmodel/Base.h \
		../../../framework/sofa/helper/system/config.h \
		../../../framework/sofa/helper/system/SofaOStream.h \
		../../../framework/sofa/helper/helper.h \
		../../../framework/sofa/helper/vector.h \
		../../../framework/sofa/core/objectmodel/DataPtr.h \
		../../../framework/sofa/core/objectmodel/Data.h \
		../../../framework/sofa/core/objectmodel/BaseData.h \
		../../../framework/sofa/core/core.h \
		../../../framework/sofa/core/objectmodel/DDGNode.h \
		../../../framework/sofa/core/objectmodel/BaseObjectDescription.h \
		../../../framework/sofa/core/objectmodel/BaseContext.h \
		../../../framework/sofa/core/objectmodel/Tag.h \
		../../../framework/sofa/helper/set.h \
		../../../framework/sofa/core/objectmodel/ClassInfo.h \
		../../../framework/sofa/helper/FnDispatcher.h \
		../../../framework/sofa/defaulttype/SolidTypes.h \
		../../../framework/sofa/defaulttype/defaulttype.h \
		../../../framework/sofa/defaulttype/Vec.h \
		../../../framework/sofa/helper/fixed_array.h \
		../../../framework/sofa/helper/rmath.h \
		../../../framework/sofa/defaulttype/Quat.h \
		../../../framework/sofa/helper/Quater.h \
		../../../framework/sofa/defaulttype/Mat.h \
		../../../framework/sofa/defaulttype/SparseConstraintTypes.h \
		../../../framework/sofa/core/BehaviorModel.h \
		../../../framework/sofa/core/componentmodel/behavior/MechanicalState.h \
		../../../framework/sofa/core/componentmodel/behavior/BaseMechanicalState.h \
		../../../framework/sofa/defaulttype/BaseMatrix.h \
		../../../framework/sofa/defaulttype/BaseVector.h \
		../../../framework/sofa/core/componentmodel/behavior/State.h \
		../../../framework/sofa/defaulttype/DataTypeInfo.h \
		../../../framework/sofa/core/componentmodel/behavior/BaseMechanicalMapping.h \
		../../../modules/sofa/component/forcefield/shells/TriangularBendingFEMForceField.h \
		../../../framework/sofa/core/componentmodel/behavior/ForceField.h \
		../../../framework/sofa/core/componentmodel/behavior/BaseForceField.h \
		../../../framework/sofa/defaulttype/VecTypes.h \
		../../../framework/sofa/defaulttype/RigidTypes.h \
		../../../framework/sofa/core/componentmodel/topology/BaseMeshTopology.h \
		../../../framework/sofa/core/componentmodel/topology/Topology.h \
		../../../framework/sofa/core/objectmodel/DataFileName.h \
		../../../framework/sofa/helper/system/FileRepository.h \
		../../../modules/sofa/component/topology/TriangleData.h \
		../../../framework/sofa/helper/system/thread/CTime.h \
		../../../modules/sofa/component/topology/TriangleSubdivisionTopologicalMapping.h \
		../../../framework/sofa/core/componentmodel/topology/TopologicalMapping.h \
		../../../modules/sofa/component/topology/PointData.h \
		../../../modules/sofa/component/component.h \
		../../../modules/sofa/component/topology/EdgeData.h \
		../../../modules/sofa/component/topology/TetrahedronData.h \
		../../../modules/sofa/component/container/MechanicalObject.h \
		../../../framework/sofa/core/objectmodel/XDataPtr.h \
		../../../framework/sofa/core/objectmodel/VDataPtr.h \
		../../../framework/sofa/defaulttype/LaparoscopicRigidTypes.h \
		../../../framework/sofa/core/componentmodel/behavior/Mass.h \
		../../../framework/sofa/core/componentmodel/behavior/BaseMass.h \
		../../../modules/sofa/component/topology/TriangleSetTopologyContainer.h \
		../../../modules/sofa/component/topology/EdgeSetTopologyContainer.h \
		../../../modules/sofa/component/topology/PointSetTopologyContainer.h \
		../../../framework/sofa/core/componentmodel/topology/BaseTopology.h \
		../../../framework/sofa/core/componentmodel/topology/BaseTopologyObject.h \
		../../../modules/sofa/component/collision/MinProximityIntersection.h \
		../../../modules/sofa/component/collision/DiscreteIntersection.h \
		../../../framework/sofa/core/componentmodel/collision/Intersection.h \
		../../../framework/sofa/core/CollisionModel.h \
		../../../framework/sofa/core/CollisionElement.h \
		../../../framework/sofa/core/componentmodel/collision/DetectionOutput.h \
		../../../modules/sofa/component/collision/SphereModel.h \
		../../../modules/sofa/component/collision/PointModel.h \
		../../../modules/sofa/component/collision/LocalMinDistanceFilter.h \
		../../../framework/sofa/defaulttype/Vec3Types.h \
		../../../modules/sofa/component/collision/LineModel.h \
		../../../modules/sofa/component/collision/TriangleModel.h \
		../../../modules/sofa/component/collision/CubeModel.h \
		../../../modules/sofa/component/collision/RayModel.h \
		../../../modules/sofa/component/collision/SphereTreeModel.h \
		../../../modules/sofa/component/collision/DistanceGridCollisionModel.h \
		../../../modules/sofa/component/container/DistanceGrid.h \
		../../../framework/sofa/helper/io/Mesh.h \
		../../../framework/sofa/helper/Factory.h \
		../../../modules/sofa/component/topology/RegularGridTopology.h \
		../../../modules/sofa/component/topology/GridTopology.h \
		../../../modules/sofa/component/topology/MeshTopology.h \
		../../../modules/sofa/component/topology/SparseGridTopology.h \
		../../../framework/sofa/helper/MarchingCubeUtility.h \
		../../../modules/sofa/component/container/VoxelGridLoader.h \
		../../../modules/sofa/component/container/MeshLoader.h \
		../../../framework/sofa/helper/io/MeshTopologyLoader.h \
		../../../modules/sofa/component/collision/TetrahedronModel.h \
		../../../modules/sofa/component/forcefield/ConstantForceField.h \
		../../../modules/sofa/component/topology/PointSubset.h \
		../../../framework/sofa/core/componentmodel/behavior/MechanicalMapping.inl \
		../../../framework/sofa/core/Mapping.inl \
		../../../framework/sofa/core/componentmodel/behavior/MappedModel.h \
		../../../framework/sofa/core/ObjectFactory.h \
		../../../framework/sofa/core/objectmodel/ContextObject.h \
		../../../framework/sofa/core/VisualModel.h \
		../../../framework/sofa/core/componentmodel/behavior/InteractionForceField.h \
		../../../framework/sofa/core/componentmodel/behavior/BaseConstraint.h \
		../../../framework/sofa/core/componentmodel/behavior/BaseLMConstraint.h \
		../../../framework/sofa/core/componentmodel/behavior/OdeSolver.h \
		../../../framework/sofa/core/componentmodel/behavior/MultiVector.h \
		../../../framework/sofa/core/componentmodel/behavior/MultiMatrix.h \
		../../../framework/sofa/core/componentmodel/behavior/LinearSolver.h \
		../../../framework/sofa/core/componentmodel/behavior/MasterSolver.h \
		../../../framework/sofa/core/componentmodel/behavior/BaseController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OBJ/release/BendingPlateMechanicalMapping.o mapping/BendingPlateMechanicalMapping.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

